version: '3.8'

services:
  fastapi:
    image: your_dockerhub_id/hellaw_fastapi:latest
    container_name: hellaw_fastapi
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
