name: Deploy FastAPI to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # Docker 이미지 빌드
      - name: Build Docker image
        run: docker build -t hellaw_fastapi .

      # DockerHub에 로그인
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # DockerHub에 푸시
      - name: Push Docker image
        run: |
          docker tag hellaw_fastapi ${{ secrets.DOCKER_USERNAME }}/hellaw_fastapi:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/hellaw_fastapi:latest

      # 원격 서버 배포
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu/HellawFastAPI
            docker pull ${{ secrets.DOCKER_USERNAME }}/hellaw_fastapi:latest
            docker-compose down
            docker-compose up -d
